# Generated by Django 5.2 on 2025-07-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_review_product_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to=''),
        ),
    ]
